# Generated by Django 5.0 on 2023-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
            ],
            options={
                'verbose_name': 'Запросы для связи',
                'verbose_name_plural': 'Запрос для связи',
            },
        ),
    ]
