# Generated by Django 5.0 on 2023-12-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotact',
            options={'verbose_name': 'Запросы для обратной связи', 'verbose_name_plural': 'Запрос для обратной связи'},
        ),
    ]
