# Generated by Django 5.0 on 2023-12-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_cotact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
            ],
            options={
                'verbose_name': 'Дополнительные данные для обработки',
                'verbose_name_plural': 'Дополнительные данные',
            },
        ),
    ]
