# Generated by Django 5.0 on 2023-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
            ],
            options={
                'verbose_name': 'Дополнительные данные для обработки',
                'verbose_name_plural': 'Дополнительные данные',
            },
        ),
        migrations.AlterModelOptions(
            name='contact_2',
            options={'verbose_name': 'Заказать звонки', 'verbose_name_plural': 'Заказать звонк'},
        ),
    ]
