# Generated by Django 5.0 on 2023-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_slide_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects_image', verbose_name='Логотип партнера')),
                ('clik', models.URLField(verbose_name='Ссылка на партнера')),
            ],
        ),
    ]
