# Generated by Django 5.0 on 2023-12-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
