# Generated by Django 5.0 on 2023-12-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_alter_partners_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='clik',
        ),
    ]
