# Generated by Django 5.0 on 2023-12-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Слайд (информация об обекте)', 'verbose_name_plural': 'Слайды и информация об обекте'},
        ),
    ]
