# Generated by Django 5.0 on 2023-12-25 14:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_alter_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='ImageGellery_image2', verbose_name='Первая фотография')),
                ('image2', models.ImageField(upload_to='ImageGellery_image1', verbose_name='Вторая фотография')),
            ],
        ),
    ]
