# Generated by Django 5.0 on 2023-12-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_imagegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Галерея с фотографиями', 'verbose_name_plural': 'Галерея с фотографиями'},
        ),
    ]
