# Generated by Django 5.0 on 2023-12-25 16:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_imagegallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descrioptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='Number1_image', verbose_name='Фоновая фотография')),
                ('image2', models.ImageField(upload_to='Number_image2', verbose_name='Основная фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Приемущество')),
                ('descrioption', ckeditor.fields.RichTextField(verbose_name='Описание о приемуществе')),
            ],
        ),
    ]
