# Generated by Django 5.0 on 2023-12-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='one',
            options={'verbose_name': 'Приемущество - 1', 'verbose_name_plural': 'Приемущество - 1'},
        ),
    ]
