# Generated by Django 5.0 on 2023-12-25 18:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_alter_one_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SlideTwo_image', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Приемущество - 2',
                'verbose_name_plural': 'Приемущество - 2',
            },
        ),
    ]
