# Generated by Django 5.0 on 2023-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
