# Generated by Django 5.0 on 2023-12-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_setting_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='compani6',
            new_name='ompani6',
        ),
    ]
