# Generated by Django 5.0 on 2023-12-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_compani6_menu_ompani6'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Менюшка', 'verbose_name_plural': 'Меню'},
        ),
    ]
