# Generated by Django 5.0 on 2023-12-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_2',
            field=models.ImageField(default=1, upload_to='about_image_2', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about_image', verbose_name='Главная фотография'),
        ),
    ]
