# Generated by Django 5.0 on 2023-12-25 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_about_image_2_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация и достижение')),
                ('descriptions_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация и достижение')),
                ('descriptions_3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация и достижение')),
                ('descriptions_4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация и достижение')),
                ('descriptions_5', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация и достижение')),
                ('descriptions_6', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация и достижение')),
            ],
        ),
    ]
