# Generated by Django 5.0 on 2023-12-25 09:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='infoPlus_image', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_5', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_6', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_7', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_8', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_9', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_10', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
                ('descriptions_11', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='приемущесво')),
            ],
            options={
                'verbose_name': 'Приемущесво',
                'verbose_name_plural': 'Приемущесво',
            },
        ),
    ]
