# Generated by Django 5.0 on 2023-12-25 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_infoplus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Товар и полная характеристика')),
                ('image', models.ImageField(upload_to='Options_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Выбор товара',
                'verbose_name_plural': 'Выбор товаров',
            },
        ),
    ]
