# Generated by Django 5.0 on 2023-12-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название товара товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
