# Generated by Django 5.0 on 2023-12-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_option_name_alter_option_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
