# Generated by Django 5.0 on 2023-12-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_choice_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='titlle',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='choice',
            name='description1',
            field=models.CharField(default=1, max_length=255, verbose_name='Характериска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='description2',
            field=models.CharField(default=1, max_length=255, verbose_name='Характериска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='description3',
            field=models.CharField(default=1, max_length=255, verbose_name='Характериска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='description4',
            field=models.CharField(default=1, max_length=255, verbose_name='Характериска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='description5',
            field=models.CharField(default=1, max_length=255, verbose_name='Характериска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='description6',
            field=models.CharField(default=1, max_length=255, verbose_name='Характериска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='title1',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='title2',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='title3',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='title4',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='title5',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='title6',
            field=models.CharField(default=1, max_length=255, verbose_name='Информация'),
            preserve_default=False,
        ),
    ]
